version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 25
    schedule:
      interval: "monthly"
      time: "00:00"

    groups:
      eslint:
        patterns:
          - 'eslint*'
          - 'globals'
          - '@eslint/*'
          - '@typescript-eslint/*'
          - '@rushstack/eslint-patch'
          - '@types/eslint'
          - 'typescript-eslint'
      stylelint:
        patterns:
          - 'stylelint*'
      vue:
        patterns:
          - 'vue*'
          - '@vue/*'
      vite:
        patterns:
          - 'vite*'
          - '@vitejs/*'
      vueuse:
        patterns:
          - '@vueuse/*'
