compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

packageExtensions:
  "@vitejs/plugin-vue-jsx@*":
    dependencies:
      vite: "*"

pnpEnableEsmLoader: true

preferReuse: true

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.6.0.cjs
