compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

pnpEnableEsmLoader: true

preferReuse: true

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.3.0.cjs

packageExtensions:
  "@vitejs/plugin-vue-jsx@*":
    dependencies:
      vite: "*"
